version: '3.8'

services:
  # O Servidor que vai rodar o seu código PHP
  app:
    image: php:8.2-apache
    container_name: moneylife_php
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html/
    
  # O Banco de Dados do MoneyLife
  db:
    image: mysql:8.0
    container_name: moneylife_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moneylife_db
      MYSQL_USER: victor_admin
      MYSQL_PASSWORD: Victor221203_